ERPractical/ERPractical/Controllers/MarkController.cs
using ERPractical.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERPractical.Controllers
{
    public class MarkController : Controller
    {
        private ERTutorialDB context;
        public MarkController(ERTutorialDB _context)
        {
            context = _context;
        }

        public IActionResult Deletes(int markId)
        {
            MarkModel mark = context.Marks.Where(x => x.MarkId == markId).Select(x => new MarkModel()
            {
                MarkId = x.MarkId,
                StudentId = x.StudentId,

                SubjectId = x.SubjectId,
                Obtainedmark = x.Obtainedmark



            }).FirstOrDefault();
            return View(mark);
        }
        [HttpPost]
        public IActionResult Deletes(MarkModel mark)
        {
            Mark markRow = new Mark();
            markRow = context.Marks.Where(x => x.MarkId == mark.MarkId).FirstOrDefault();

            context.Marks.Remove(markRow);
            context.SaveChanges();
            return RedirectToAction("Marks");
        }
        public IActionResult Creates()
        {
            var Students = context.Students.Select(student => new StudentModel
            {
                StudentId = student.StudentId,
                StudentName = student.StudentName,
                Batch = student.Batch,
                ContactNumber = student.ContactNumber
            }).ToList();
            ViewBag.Students = new SelectList(Students, "StudentId", "StudentName");

            var Subjects = context.Subjects.Select(x => new SubjectModel
            {
                SubjectId = x.SubjectId,
                SubjectName = x.SubjectName
            }).ToList();
            ViewBag.Subjects = new SelectList(Subjects, "SubjectId", "SubjectName");
            return View(new MarkModel());
        }

        [HttpPost]
        public IActionResult Creates(MarkModel mark)
        {
            Mark markRow = new Mark();
            markRow.MarkId = mark.MarkId;
            markRow.StudentId = mark.StudentId;

            markRow.Obtainedmark = mark.Obtainedmark;

            markRow.SubjectId = mark.SubjectId;


            context.Marks.Add(markRow);
            context.SaveChanges();
            return RedirectToAction("Marks");
        }
        public IActionResult Marks_Details(int markId)
        {

            MarkModel mark = context.Marks.Where(x => x.MarkId == markId).Select(x => new MarkModel()
            {
                MarkId = x.MarkId,
                SubjectId = x.SubjectId,
                Obtainedmark = x.Obtainedmark,
                StudentId = x.StudentId


            }).FirstOrDefault();

            return View(mark);
        }
        public IActionResult Edits(int markId)
        {

            var Students = context.Students.Select(student => new StudentModel
            {
                StudentId = student.StudentId,
                StudentName = student.StudentName,
                Batch = student.Batch,
                ContactNumber = student.ContactNumber
            }).ToList();
            ViewBag.Students = new SelectList(Students, "StudentId", "StudentName");

            var Subjects = context.Subjects.Select(x => new SubjectModel
            {
                SubjectId = x.SubjectId,
                SubjectName = x.SubjectName
            }).ToList();
            ViewBag.Subjects = new SelectList(Subjects, "SubjectId", "SubjectName");

            MarkModel mark = context.Marks.Where(x => x.MarkId == markId).Select(x => new MarkModel()
            {
                MarkId = x.MarkId,
                StudentId = x.StudentId,

                Obtainedmark = x.Obtainedmark,

                SubjectId = x.SubjectId,


            }).FirstOrDefault();
            return View(mark);
        }
        [HttpPost]
        public IActionResult Edits(MarkModel mark)
        {
            Mark markRow = new Mark();
            markRow.StudentId = mark.StudentId;
            markRow.MarkId = mark.MarkId;

            markRow.SubjectId = mark.SubjectId;
            markRow.Obtainedmark = mark.Obtainedmark;



            context.Marks.Attach(markRow);
            context.Entry(markRow).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Marks");
        }
        public IActionResult Marks()

        {
            List<MarkModel> marks = (from M in context.Marks
                                     join S in context.Students on M.StudentId equals S.StudentId
                                     join Su in context.Subjects on M.SubjectId equals Su.SubjectId
                                     select new MarkModel()
                                     {
                                         MarkId = M.MarkId,
                                         StudentId = M.StudentId,
                                         StudentName = S.StudentName,
                                         SubjectName = Su.SubjectName,

                                         Obtainedmark = M.Obtainedmark,

                                         SubjectId = M.SubjectId


                                     }).ToList();
            return View(marks);

        }
        public IActionResult StudentMarks(int StudentId)
        {
           string stdId = StudentId.ToString();
            List<MarksModels> marks = context.MarksModels.FromSqlRaw("SpGetStudentMarks "+ StudentId.ToString()).ToList();
            return View(marks);

        }
    }
}

ERPractical/ERPractical/Controllers/StudentController.cs
using ERPractical.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;

namespace ERPractical.Controllers
{
    public class StudentController : Microsoft.AspNetCore.Mvc.Controller
    {
        private ERTutorialDB context;
        public StudentController(ERTutorialDB _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View(new StudentModel());
        }
        [HttpPost]
        public IActionResult Create(StudentModel student)
        {
            Student studentRow = new Student();
            studentRow.StudentId = student.StudentId;
            studentRow.StudentName = student.StudentName;
            studentRow.Address = student.Address;
            studentRow.Batch = student.Batch;
            studentRow.ContactNumber = student.ContactNumber;
            context.Add(studentRow);
            //  context.Entry(studentRow).State = EntityState.Added;
            context.SaveChanges();
            return RedirectToAction("students");
        }

        public IActionResult Delete(int studentId)
        {
            StudentModel student = context.Students.Where(x => x.StudentId == studentId).Select(x => new StudentModel()
            {
                StudentId = x.StudentId,
                StudentName = x.StudentName,

                Address = x.Address,

                Batch = x.Batch,
                ContactNumber = x.ContactNumber


            }).FirstOrDefault();
            return View(student);
        }
        [HttpPost]
        public IActionResult Delete(StudentModel student)
        {
            Student studentRow = new Student();
            studentRow = context.Students.Where(x => x.StudentId == student.StudentId).FirstOrDefault();

            context.Students.Remove(studentRow);
            context.SaveChanges();
            return RedirectToAction("Students");
        }
        public IActionResult Edit(int studentId)
        {
            StudentModel student = context.Students.Where(x => x.StudentId == studentId).Select(x => new StudentModel()
            {
                StudentId = x.StudentId,
                StudentName = x.StudentName,

                Address = x.Address,

                Batch = x.Batch,
                ContactNumber = x.ContactNumber


            }).FirstOrDefault();
            return View(student);
        }
        [HttpPost]
        public IActionResult Edit(StudentModel student)
        {
            Student studentRow = new Student();
            studentRow.StudentId = student.StudentId;
            studentRow.StudentName = student.StudentName;

            studentRow.Address = student.Address;

            studentRow.Batch = student.Batch;
            studentRow.ContactNumber = student.ContactNumber;

            context.Students.Attach(studentRow);
            context.Entry(studentRow).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Students");
        }
        public IActionResult Details(int studentId)
        {
            StudentModel student = context.Students.Where(x => x.StudentId == studentId).Select(x => new StudentModel()
            {
                StudentId = x.StudentId,
                StudentName = x.StudentName,
                Address = x.Address,
                Batch = x.Batch,
                ContactNumber = x.ContactNumber


            }).FirstOrDefault();

            return View(student);
        }




        public IActionResult Students()
        {
            List<StudentModel> students = context.Students.Select(student => new StudentModel()
            {
                StudentId = student.StudentId,
                StudentName = student.StudentName,

                Address = student.Address,

                Batch = student.Batch,
                ContactNumber = student.ContactNumber


            }
            )
                .ToList();
            return View(students);




        }

    }
}

ERPractical/ERPractical/Views/Student/Create.cshtml
@model StudentModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Batch" class="control-label"></label>
                <input asp-for="Batch" class="form-control" />
                <span asp-validation-for="Batch" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Students">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ERPractical/ERPractical/Views/Student/Delete.cshtml
@model ERPractical.Models.StudentModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentModel</h4>
    <hr />
    <form asp-action="Delete">
        <dl class="row">
           
                @Html.HiddenFor(model => model.StudentId)
         
          
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StudentName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StudentName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Batch)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Batch)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ContactNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ContactNumber)
            </dd>
        </dl>


        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Students">Back to List</a>
    </form>
</div>

ERPractical/ERPractical/Views/Student/Details.cshtml
@model ERPractical.Models.StudentModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StudentModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Batch)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Batch)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>
    </dl>
</div>
<div>
  
    <a asp-action="Students">Back to List</a>
</div>

ERPractical/ERPractical/Views/Student/Edit.cshtml
@model ERPractical.Models.StudentModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StudentModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                
                <input type=hidden asp-for="StudentId" class="form-control" />
           
            </div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Batch" class="control-label"></label>
                <input asp-for="Batch" class="form-control" />
                <span asp-validation-for="Batch" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Students">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ERPractical/ERPractical/Views/Student/Students.cshtml
@model IEnumerable<StudentModel>

@{
    ViewData["Title"] = "Students";
    int studentCounter = 1;
}

<h1>Students</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                SN
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Batch)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @studentCounter
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Batch)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { studentId = item.StudentId }) |
                @Html.ActionLink("Details", "Details", new { studentId = item.StudentId }) |
                @Html.ActionLink("Delete", "Delete", new { studentId = item.StudentId })|
                @Html.ActionLink("Marks", "StudentMarks","Mark", new { studentId = item.StudentId })
            </td>
        </tr>
        studentCounter++;
}
    </tbody>
</table>